
package plataformainteroperabilidad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ciudadanos", targetNamespace = "http://webservices.samples.jboss.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ciudadanos {


    /**
     * 
     * @param arg0
     * @return
     *     returns plataformainteroperabilidad.Ciudadano
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtPersonaPorDoc", targetNamespace = "http://webservices.samples.jboss.org/", className = "plataformainteroperabilidad.ObtPersonaPorDoc")
    @ResponseWrapper(localName = "obtPersonaPorDocResponse", targetNamespace = "http://webservices.samples.jboss.org/", className = "plataformainteroperabilidad.ObtPersonaPorDocResponse")
    public Ciudadano obtPersonaPorDoc(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
