
package plataformainteroperabilidad;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ciudadanos", targetNamespace = "http://services.tse.facultad/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ciudadanos {


    /**
     * 
     * @param arg0
     * @return
     *     returns plataformainteroperabilidad.Ciudadano
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://services.tse.facultad/ciudadanos/obtPersonaPorDocRequest", output = "http://services.tse.facultad/ciudadanos/obtPersonaPorDocResponse")
    public Ciudadano obtPersonaPorDoc(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
